# Generated by Django 5.1.6 on 2025-04-28 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_mentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
